### ISSUE TITLE
openrave does not compile on armhf

### ISSUE THREAD

**Issue by tfoote** [tork-a/openrave_planning-release#1]
It looks like there's a missing dependency specific to armhf. 

http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__openrave__ubuntu_trusty_armhf__binary/162/console

```
# BEGIN SUBSECTION: append build timestamp
03:04:41 Invoking 'debchange -v 0.0.3-0trusty-20161124-030441-0800 -p -D trusty -u high -m Append timestamp when binarydeb was built.' in '/tmp/binarydeb/ros-indigo-openrave-0.0.3'
03:04:44 # END SUBSECTION
03:05:17 Looking for the '.dsc' file of package 'ros-indigo-openrave' with version '0.0.3-0'
03:05:38 Traceback (most recent call last):
03:05:38   File "/usr/lib/python3/dist-packages/apt/cache.py", line 198, in __getitem__
03:05:38     return self._weakref[key]
03:05:38   File "/usr/lib/python3.4/weakref.py", line 125, in __getitem__
03:05:38     o = self.data[key]()
03:05:38 KeyError: 'libsoqt4-dev'
03:05:38 
03:05:38 During handling of the above exception, another exception occurred:
03:05:38 
03:05:38 Traceback (most recent call last):
03:05:38   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 162, in <module>
03:05:38     main()
03:05:38   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 84, in main
03:05:38     apt_cache, debian_pkg_names)
03:05:38   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 134, in get_binary_package_versions
03:05:38     pkg = apt_cache[debian_pkg_name]
03:05:38   File "/usr/lib/python3/dist-packages/apt/cache.py", line 205, in __getitem__
03:05:38     raise KeyError('The cache has no package named %r' % key)
03:05:38 KeyError: "The cache has no package named 'libsoqt4-dev'"
03:05:38 Build step 'Execute shell' marked build as failure
03:05:38 [ssh-agent] Stopped.
03:05:38 [description-setter] Could not determine description.
03:05:38 Sending e-mails to: ros-buildfarm-indigo@googlegroups.com tfoote+buildfarm@osrfoundation.org
03:05:38 Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
03:05:38 Finished: FAILURE
```

**Comment by k-okada** [comment]
Thanks, this is because of libsoqt( http://packages.ubuntu.com/trusty/libsoqt-dev-common
) not available on armhf, Once https://bugs.launchpad.net/ubuntu/+source/soqt/+bug/791322/comments/2 or other solution is accepted, we can release openrave on armhf
